apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-calculator
  labels:
    app: bmi-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bmi-calculator
  template:
    metadata:
      labels:
        app: bmi-calculator
    spec:
      containers:
      - name: bmi-calculator
        image: IMAGE_NAME:IMAGE_TAG
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: bmi-calculator
spec:
  type: NodePort
  selector:
    app: bmi-calculator
  ports:
  - port: 5000




